apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-db
  annotations:
    k8s.v1.cni.cncf.io/networks: lan-net # Connexion exclusive au segment LAN
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          interfaces:
            - name: default
              masquerade: {}
            - name: lan-nic
              bridge: {}     # Interface dans le réseau de données
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
      networks:
        - name: default
          pod: {}
        - name: lan-nic
          multus:
            networkName: lan-net
      volumes:
        - containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
          name: containerdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm-db-uadb
              packages:
                - mysql-server
              runcmd:
                # 1. Configurer l'IP statique LAN (192.168.10.10)
                - ip addr add 192.168.10.10/24 dev eth1
                - ip link set eth1 up
                # 2. Autoriser MySQL à écouter sur le réseau LAN
                - sed -i "s/127.0.0.1/0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
                - systemctl restart mysql
                # 3. Exécuter votre script SQL (si importé dans cloud-init)
                # (Alternative : mysql < /home/ubuntu/init-db.sql)
          name: cloudinitdisk
