apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-firewall
  labels:
    special: firewall-gateway
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1Gi
        devices:
          autoattachGraphicsDevice: false
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
        machine:
          type: pc-q35-rhel9.6.0
      networks:
        - name: default
          pod: {}
      volumes:
        - containerDisk:
            image: 'quay.io/containerdisks/ubuntu:22.04'
          name: containerdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: ubuntu
              password: UadbCloud2024!
              chpasswd: { expire: false }
              ssh_pwauth: true
              hostname: firewall-uadb
              runcmd:
                - apt-get update && apt-get install -y iptables
                - echo 1 > /proc/sys/net/ipv4/ip_forward
                - iptables -P INPUT ACCEPT
          name: cloudinitdisk
