apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-web
  labels:
    app: uadb-web
spec:
  running: true
  template:
    spec:
      domain:
        devices:
          interfaces:
            - name: default
              masquerade: {} # Utilise le réseau autorisé par la Sandbox
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
      networks:
        - name: default
          pod: {}
      volumes:
        - containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
          name: containerdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm-web-uadb
              packages:
                - nodejs
                - npm
                - git
              write_files:
                - content: |
                    # Votre code server.js sera généré ici
                  path: /home/ubuntu/app/server.js
              runcmd:
                # 1. Préparation du dossier de l'application
                - mkdir -p /home/ubuntu/app
                - cd /home/ubuntu/app
                # 2. Installation des dépendances
                - npm init -y
                - npm install express mysql2
                # 3. Lancement de l'application en arrière-plan sur le port 3000
                - nohup node /home/ubuntu/app/server.js > /home/ubuntu/app.log 2>&1 &
          name: cloudinitdisk
